version: '2.3'
services:
  ubuntu-init-14.04:
    image: ${DOCKER_REPO}/ubuntu-init:14.04${DOCKER_REV_TAG:-}
    build:
      context: ubuntu-init
      cache_from:
        - ${DOCKER_REPO}/ubuntu-init:14.04
      dockerfile: Dockerfile-14.04
  ubuntu-init-16.04:
    image: ${DOCKER_REPO}/ubuntu-init:16.04${DOCKER_REV_TAG:-}
    build:
      context: ubuntu-init
      cache_from:
        - ${DOCKER_REPO}/ubuntu-init:16.04
      args:
        UBUNTU_VERSION: '16.04'
  ubuntu-init-18.04:
    image: ${DOCKER_REPO}/ubuntu-init:18.04${DOCKER_REV_TAG:-}
    build:
      context: ubuntu-init
      cache_from:
        - ${DOCKER_REPO}/ubuntu-init:18.04
      args:
        UBUNTU_VERSION: '18.04'
  ubuntu-init-python-14.04:
    image: ${DOCKER_REPO}/ubuntu-init-python:14.04${DOCKER_REV_TAG:-}
    build:
      context: ubuntu-init-python
      cache_from:
        - ${DOCKER_REPO}/ubuntu-init-python:14.04
      dockerfile: Dockerfile-14.04
    depends_on:
      - ubuntu-init-14.04
  ubuntu-init-python-16.04:
    image: ${DOCKER_REPO}/ubuntu-init-python:16.04${DOCKER_REV_TAG:-}
    build:
      context: ubuntu-init-python
      cache_from:
        - ${DOCKER_REPO}/ubuntu-init-python:16.04
      args:
        UBUNTU_VERSION: '16.04'
    depends_on:
      - ubuntu-init-16.04
  ubuntu-init-python-18.04:
    image: ${DOCKER_REPO}/ubuntu-init-python:18.04${DOCKER_REV_TAG:-}
    build:
      context: ubuntu-init-python
      cache_from:
        - ${DOCKER_REPO}/ubuntu-init-python:18.04
      args:
        UBUNTU_VERSION: '18.04'
    depends_on:
      - ubuntu-init-18.04
  ubuntu-init-python3-18.04:
    image: ${DOCKER_REPO}/ubuntu-init-python3:18.04${DOCKER_REV_TAG:-}
    build:
      context: ubuntu-init-python3
      cache_from:
        - ${DOCKER_REPO}/ubuntu-init-python3:18.04
      args:
        UBUNTU_VERSION: '18.04'
    depends_on:
      - ubuntu-init-18.04
  jdk11-datadog-agent:
    image: ${DOCKER_REPO}/jdk11-datadog-agent:11.0.16-jre-slim-buster-datadog-agent${DOCKER_REV_TAG:-}
    build:
      context: jdk11-datadog-agent
      cache_from:
        - ${DOCKER_REPO}/jdk11-datadog-agent:11.0.16-jre-slim-buster-datadog-agent
  flink:
    image: ${DOCKER_REPO}/flink:1.13.6-scala_2.11${DOCKER_REV_TAG:-}
    build:
      context: flink
      cache_from:
        - ${DOCKER_REPO}/flink:1.13.6-scala_2.11
      args:
        FLINK_VERSION: 1.13.6
        SCALA_VERSION_MAJOR: 2
        SCALA_VERSION_MINOR: 11
