#!/bin/sh

ppid=$$
squid_log_dir=/var/log/squid

touch \
  "${squid_log_dir}/access.log" \
  "${squid_log_dir}/cache.log" \
  "${squid_log_dir}/store.log"

chown squid:squid \
  "${squid_log_dir}/access.log" \
  "${squid_log_dir}/cache.log" \
  "${squid_log_dir}/store.log"

tail --pid "$ppid" -q -F \
  "${squid_log_dir}/access.log" \
  "${squid_log_dir}/cache.log" \
  "${squid_log_dir}/store.log" &

"$@"
