#!/bin/sh

ubuntu_version=

case "${DOCKER_TAG}" in
14.04)
  dockerfile=Dockerfile-14.04
;;
16.04)
  ubuntu_version=16.04
;;
*)
  ubuntu_version=18.04
esac

docker build \
  --build-arg UBUNTU_VERSION="${ubuntu_version}" \
  -f "${DOCKERFILE_PATH}" \
  -t "${IMAGE_NAME}" \
  .
